#!/usr/bin/env bash

## Initial setup for Docksal development environment

green='\033[0;32m'
yellow='\033[1;33m'
NC='\033[0m'


#-------- Runtime ----------

init_project ()
{
    # Reset containers
    while getopts ":r" flag; do
      case $flag in
        r)
          echo -e "\n${yellow}Resetting containers${NC}"
          fin project reset --force
          ;;
        \?)
          echo "Invalid option: -$OPTARG" >&2
          ;;
      esac
    done

    # Strip off processed options, leaving just arguments remaining.
    shift $((OPTIND-1))

    # Install Node packages
    echo -e "\n${yellow}Installing project Node dependencies${NC}"
    cd "$PROJECT_ROOT"
    if [ -d "package-lock.json" ]; then
      fin exec npm ci || exit 1
    else
      fin exec npm i || exit 1
    fi

    # Initial Webpack Bundle
    echo -e "\n${yellow}Initial Weback Bundle${NC}"
    cd "$PROJECT_ROOT"
    fin exec npm run build || exit 1
}

#-------------------------- Execution --------------------------------

if [[ "$PROJECT_ROOT" == "" ]]; then
	echo-red "\$PROJECT_ROOT is not set"
	exit 1
fi

if [[ $DOCKER_RUNNING == "true" ]]; then
	echo -e "Step 1 ${NC}${green} Recreating services...${NC}"
	fin reset -f
else
	echo -e "Step 1 ${NC}${green} Creating services...${NC}"
	fin up
fi

# Project initialization steps
echo -e "${green} Step 2 ${NC}${green} Initializing local project...${NC}"
init_project

echo -en "\n${green} DONE! ${NC}\n"
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."